"""fase 0 base

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 17:10:15.995161
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geografia_estado',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('plantilla_algoritmo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('plantilla_clasificacion_programatica',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('plantilla_conac',
    sa.Column('nivel', sa.String(length=24), nullable=False),
    sa.Column('padre_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['padre_id'], ['plantilla_conac.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nivel', 'clave')
    )
    op.create_index(op.f('ix_plantilla_conac_padre_id'), 'plantilla_conac', ['padre_id'], unique=False)
    op.create_table('plantilla_dimension',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('plantilla_frecuencia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('plantilla_grupo_edad',
    sa.Column('edad_min', sa.Integer(), nullable=True),
    sa.Column('edad_max', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('plantilla_nivel_socioeconomico',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('subdominio_reservado',
    sa.Column('subdominio', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('subdominio')
    )
    op.create_table('super_admin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('geografia_municipio',
    sa.Column('estado_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['estado_id'], ['geografia_estado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estado_id', 'clave')
    )
    op.create_index(op.f('ix_geografia_municipio_estado_id'), 'geografia_municipio', ['estado_id'], unique=False)
    op.create_table('municipio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('subdominio', sa.String(length=63), nullable=False),
    sa.Column('estado_republica_id', sa.Uuid(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('imagen_login_url', sa.Text(), nullable=True),
    sa.Column('color_boton', sa.Enum('default', 'primary', 'info', 'success', 'warning', 'danger', 'dark', name='colorboton', native_enum=False, length=32), nullable=False),
    sa.Column('mostrar_logos', sa.Boolean(), nullable=False),
    sa.Column('duracion_sesion_dias', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'suspendido', name='estadomunicipio', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['estado_republica_id'], ['geografia_estado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdominio')
    )
    op.create_table('bitacora',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('municipio_id', sa.Uuid(), nullable=True),
    sa.Column('actor_tipo', sa.Enum('usuario', 'super_admin', name='actortipo', native_enum=False, length=32), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('accion', sa.Text(), nullable=False),
    sa.Column('entidad', sa.Text(), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('detalle', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bitacora_municipio_id'), 'bitacora', ['municipio_id'], unique=False)
    op.create_table('catalogo_municipio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('padre_id', sa.Uuid(), nullable=True),
    sa.Column('datos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('municipio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['catalogo_municipio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'tipo', 'clave', 'padre_id')
    )
    op.create_index(op.f('ix_catalogo_municipio_municipio_id'), 'catalogo_municipio', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_catalogo_municipio_padre_id'), 'catalogo_municipio', ['padre_id'], unique=False)
    op.create_index(op.f('ix_catalogo_municipio_tipo'), 'catalogo_municipio', ['tipo'], unique=False)
    op.create_table('geografia_localidad',
    sa.Column('municipio_geo_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_geo_id'], ['geografia_municipio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_geo_id', 'clave')
    )
    op.create_index(op.f('ix_geografia_localidad_municipio_geo_id'), 'geografia_localidad', ['municipio_geo_id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Enum('informes', 'padron', 'presupuestacion', 'control_presupuestal', 'indicadores', 'alcalde', 'administrador', name='tipousuario', native_enum=False, length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('municipio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'usuario')
    )
    op.create_index(op.f('ix_usuario_municipio_id'), 'usuario', ['municipio_id'], unique=False)
    op.create_table('sesion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('super_admin_id', sa.Uuid(), nullable=True),
    sa.Column('municipio_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(usuario_id IS NULL) <> (super_admin_id IS NULL)', name='ck_sesion_un_solo_actor'),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['super_admin_id'], ['super_admin.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesion_super_admin_id'), 'sesion', ['super_admin_id'], unique=False)
    op.create_index(op.f('ix_sesion_usuario_id'), 'sesion', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesion_usuario_id'), table_name='sesion')
    op.drop_index(op.f('ix_sesion_super_admin_id'), table_name='sesion')
    op.drop_table('sesion')
    op.drop_index(op.f('ix_usuario_municipio_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_geografia_localidad_municipio_geo_id'), table_name='geografia_localidad')
    op.drop_table('geografia_localidad')
    op.drop_index(op.f('ix_catalogo_municipio_tipo'), table_name='catalogo_municipio')
    op.drop_index(op.f('ix_catalogo_municipio_padre_id'), table_name='catalogo_municipio')
    op.drop_index(op.f('ix_catalogo_municipio_municipio_id'), table_name='catalogo_municipio')
    op.drop_table('catalogo_municipio')
    op.drop_index(op.f('ix_bitacora_municipio_id'), table_name='bitacora')
    op.drop_table('bitacora')
    op.drop_table('municipio')
    op.drop_index(op.f('ix_geografia_municipio_estado_id'), table_name='geografia_municipio')
    op.drop_table('geografia_municipio')
    op.drop_table('super_admin')
    op.drop_table('subdominio_reservado')
    op.drop_table('plantilla_nivel_socioeconomico')
    op.drop_table('plantilla_grupo_edad')
    op.drop_table('plantilla_frecuencia')
    op.drop_table('plantilla_dimension')
    op.drop_index(op.f('ix_plantilla_conac_padre_id'), table_name='plantilla_conac')
    op.drop_table('plantilla_conac')
    op.drop_table('plantilla_clasificacion_programatica')
    op.drop_table('plantilla_algoritmo')
    op.drop_table('geografia_estado')
    # ### end Alembic commands ###
