"""fase 2 mir

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-02 11:18:20.418140
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arbol_causa_medio',
    sa.Column('programa_id', sa.Uuid(), nullable=False),
    sa.Column('padre_id', sa.Uuid(), nullable=True),
    sa.Column('texto_causa', sa.Text(), nullable=False),
    sa.Column('texto_medio', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['arbol_causa_medio.id'], ),
    sa.ForeignKeyConstraint(['programa_id'], ['programa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arbol_causa_medio_municipio_id'), 'arbol_causa_medio', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_arbol_causa_medio_padre_id'), 'arbol_causa_medio', ['padre_id'], unique=False)
    op.create_index(op.f('ix_arbol_causa_medio_programa_id'), 'arbol_causa_medio', ['programa_id'], unique=False)
    op.create_table('arbol_efecto_fin',
    sa.Column('programa_id', sa.Uuid(), nullable=False),
    sa.Column('padre_id', sa.Uuid(), nullable=True),
    sa.Column('texto_efecto', sa.Text(), nullable=False),
    sa.Column('texto_fin', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['arbol_efecto_fin.id'], ),
    sa.ForeignKeyConstraint(['programa_id'], ['programa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arbol_efecto_fin_municipio_id'), 'arbol_efecto_fin', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_arbol_efecto_fin_padre_id'), 'arbol_efecto_fin', ['padre_id'], unique=False)
    op.create_index(op.f('ix_arbol_efecto_fin_programa_id'), 'arbol_efecto_fin', ['programa_id'], unique=False)
    op.create_table('arbol_encabezado',
    sa.Column('programa_id', sa.Uuid(), nullable=False),
    sa.Column('problema', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('municipio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['programa_id'], ['programa.id'], ),
    sa.PrimaryKeyConstraint('programa_id')
    )
    op.create_index(op.f('ix_arbol_encabezado_municipio_id'), 'arbol_encabezado', ['municipio_id'], unique=False)
    op.create_table('elemento_matriz',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('programa_id', sa.Uuid(), nullable=False),
    sa.Column('nivel', sa.Enum('fin', 'proposito', 'componente', 'actividad', name='nivelmatriz', native_enum=False, length=32), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('padre_id', sa.Uuid(), nullable=True),
    sa.Column('resumen_narrativo', sa.Text(), nullable=False),
    sa.Column('medios_verificacion', sa.Text(), nullable=False),
    sa.Column('supuestos', sa.Text(), nullable=False),
    sa.Column('evidencia', sa.Text(), nullable=True),
    sa.Column('municipio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.ForeignKeyConstraint(['padre_id'], ['elemento_matriz.id'], ),
    sa.ForeignKeyConstraint(['programa_id'], ['programa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elemento_matriz_municipio_id'), 'elemento_matriz', ['municipio_id'], unique=False)
    op.create_index(op.f('ix_elemento_matriz_padre_id'), 'elemento_matriz', ['padre_id'], unique=False)
    op.create_index(op.f('ix_elemento_matriz_programa_id'), 'elemento_matriz', ['programa_id'], unique=False)
    op.create_index('uq_elemento_matriz_fin_proposito', 'elemento_matriz', ['programa_id', 'nivel'], unique=True, postgresql_where=sa.text("nivel IN ('fin', 'proposito')"), sqlite_where=sa.text("nivel IN ('fin', 'proposito')"))
    op.create_table('indicador',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('elemento_matriz_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.Enum('gestion', 'estrategico', name='tipoindicador', native_enum=False, length=32), nullable=False),
    sa.Column('prioritario', sa.Boolean(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('interpretacion', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Enum('eficacia', 'eficiencia', 'calidad', 'economia', name='dimensionindicador', native_enum=False, length=32), nullable=True),
    sa.Column('frecuencia_id', sa.Uuid(), nullable=True),
    sa.Column('unidad_medida', sa.Text(), nullable=False),
    sa.Column('algoritmo', sa.Enum('a_sobre_b_pct', 'a_sobre_b_menos1_pct', 'a_sobre_b', 'a', name='algoritmo', native_enum=False, length=32), nullable=True),
    sa.Column('unidad_a', sa.Text(), nullable=False),
    sa.Column('unidad_b', sa.Text(), nullable=True),
    sa.Column('rango_verde_desde', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rango_verde_hasta', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rango_amarillo_desde', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rango_amarillo_hasta', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rango_rojo_desde', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rango_rojo_hasta', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('anio_base', sa.Integer(), nullable=True),
    sa.Column('meta_administracion', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('municipio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['elemento_matriz_id'], ['elemento_matriz.id'], ),
    sa.ForeignKeyConstraint(['frecuencia_id'], ['frecuencia.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicador_elemento_matriz_id'), 'indicador', ['elemento_matriz_id'], unique=False)
    op.create_index(op.f('ix_indicador_municipio_id'), 'indicador', ['municipio_id'], unique=False)
    op.create_table('avance_mensual',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicador_id', sa.Uuid(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('valor_a', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('valor_b', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('municipio_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('mes BETWEEN 1 AND 12', name='ck_avance_mes'),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicador.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicador_id', 'anio', 'mes')
    )
    op.create_index(op.f('ix_avance_mensual_indicador_id'), 'avance_mensual', ['indicador_id'], unique=False)
    op.create_index(op.f('ix_avance_mensual_municipio_id'), 'avance_mensual', ['municipio_id'], unique=False)
    op.create_table('meta_anual',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('indicador_id', sa.Uuid(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('valor_a_programado', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('valor_b_programado', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('es_ejercicio_fiscal', sa.Boolean(), nullable=False),
    sa.Column('municipio_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicador.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicador_id', 'anio')
    )
    op.create_index(op.f('ix_meta_anual_indicador_id'), 'meta_anual', ['indicador_id'], unique=False)
    op.create_index(op.f('ix_meta_anual_municipio_id'), 'meta_anual', ['municipio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_anual_municipio_id'), table_name='meta_anual')
    op.drop_index(op.f('ix_meta_anual_indicador_id'), table_name='meta_anual')
    op.drop_table('meta_anual')
    op.drop_index(op.f('ix_avance_mensual_municipio_id'), table_name='avance_mensual')
    op.drop_index(op.f('ix_avance_mensual_indicador_id'), table_name='avance_mensual')
    op.drop_table('avance_mensual')
    op.drop_index(op.f('ix_indicador_municipio_id'), table_name='indicador')
    op.drop_index(op.f('ix_indicador_elemento_matriz_id'), table_name='indicador')
    op.drop_table('indicador')
    op.drop_index('uq_elemento_matriz_fin_proposito', table_name='elemento_matriz', postgresql_where=sa.text("nivel IN ('fin', 'proposito')"), sqlite_where=sa.text("nivel IN ('fin', 'proposito')"))
    op.drop_index(op.f('ix_elemento_matriz_programa_id'), table_name='elemento_matriz')
    op.drop_index(op.f('ix_elemento_matriz_padre_id'), table_name='elemento_matriz')
    op.drop_index(op.f('ix_elemento_matriz_municipio_id'), table_name='elemento_matriz')
    op.drop_table('elemento_matriz')
    op.drop_index(op.f('ix_arbol_encabezado_municipio_id'), table_name='arbol_encabezado')
    op.drop_table('arbol_encabezado')
    op.drop_index(op.f('ix_arbol_efecto_fin_programa_id'), table_name='arbol_efecto_fin')
    op.drop_index(op.f('ix_arbol_efecto_fin_padre_id'), table_name='arbol_efecto_fin')
    op.drop_index(op.f('ix_arbol_efecto_fin_municipio_id'), table_name='arbol_efecto_fin')
    op.drop_table('arbol_efecto_fin')
    op.drop_index(op.f('ix_arbol_causa_medio_programa_id'), table_name='arbol_causa_medio')
    op.drop_index(op.f('ix_arbol_causa_medio_padre_id'), table_name='arbol_causa_medio')
    op.drop_index(op.f('ix_arbol_causa_medio_municipio_id'), table_name='arbol_causa_medio')
    op.drop_table('arbol_causa_medio')
    # ### end Alembic commands ###
